version: "3.9"

services:
  stt-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    image: stt-service:dev
    ports: ["8000:8000"]
    volumes:
      - ./:/server
      - ./models:/root/.cache/whisper
      - ./client/web:/server/client/web:ro
    restart: unless-stopped
